metadata:
    id: hello-ocr
    language: swe

import:
    importer: text_import:parse

export:
    annotations:
        - <sentence>
        # - <token:word>
        - <token>:stanza.pos
        - <token>:ocr_correction.ocr-correction--viklofg-swedish-ocr

sparv:
    compression: none
